replicaCount: 1

image:
  repository: payment-service
  tag: "dev"
  pullPolicy: Never # because image is built locally for Kind

service:
  type: ClusterIP
  port: 3000

resources: {}

postgres:
  enabled: true
  host: payment-db
  port: 5432
  user: postgres
  password: postgres
  database: paymentdb
