# version: "3.9"

services:
  payment-api:
    container_name: payment-api
    build: .
    ports:
      - "3002:3000" # host:container
    env_file:
      - .env
    depends_on:
      - payment-db

  payment-db:
    container_name: payment-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  payment-pgadmin:
    container_name: payment-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reload.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - payment-db

volumes:
  pgdata:
