services:
  db:
    image: postgres:15
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432" # avoid clashing with local Postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  payment:
    build: .
    container_name: payment-service
    command: npm run start:dev
    env_file:
      - .env.development
    ports:
      - "${PORT:-3002}:3000" # flexible: use .env PORT or default 3002
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
